version: '2'

services:
  dev-postgres-2:
    image: postgres:9.4-alpine
    container_name: digiwhist-db-2
    restart: always
    environment:
       POSTGRES_DB: digiwhist
       POSTGRES_USER: digiwhist
       POSTGRES_PASSWORD: digiwhist
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./input-data:/input
    ports:
      - "127.0.0.1:5432:5432"
